---
header:
  - license:
      content: |
        SPDX-License-Identifier: Apache-2.0
        Copyright Authors of bpfman
    paths:
      - bpfman
    paths-ignore:
      - "**/LICENSE-*"
      - "**/target/**"
      - "**/*.toml"
      - "**/*.proto"
      - "**/*.lock"
      - "**/*.yml"
      - "**/*.md"
      - "/ven"
    comment: on-failure
