apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplicationState
metadata:
  creationTimestamp: "2025-03-31T20:38:02Z"
  finalizers:
  - bpfman.io.clbpfapplicationcontroller/finalizer
  generation: 1
  labels:
    bpfman.io/ownedByProgram: clusterbpfapplication-sample
    kubernetes.io/hostname: bpfman-deployment-control-plane
  name: clusterbpfapplication-sample-6938aab9
  ownerReferences:
  - apiVersion: bpfman.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterBpfApplication
    name: clusterbpfapplication-sample
    uid: e18c4760-7f89-48bb-ac24-2c01c9f7c7c8
  resourceVersion: "1483"
  uid: 7d8eb460-a560-4055-b1fe-5fc66e90736e
spec: {}
status:
  appLoadStatus: LoadSuccess
  conditions:
  - lastTransitionTime: "2025-03-31T20:38:54Z"
    message: The BPF application has been successfully loaded and attached
    reason: Success
    status: "True"
    type: Success
  node: bpfman-deployment-control-plane
  programs:
  - kprobe:
      links:
      - function: try_to_wake_up
        linkId: 675202769
        linkStatus: Attached
        offset: 0
        shouldAttach: true
        uuid: 4aab6ffe-ec74-4845-ab24-a54def1b555c
    name: kprobe_test
    programId: 13394
    programLinkStatus: Success
    type: KProbe
  - kretprobe:
      links:
      - function: try_to_wake_up
        linkId: 3965865826
        linkStatus: Attached
        shouldAttach: true
        uuid: 919a7317-4c47-4576-aada-f93131be7686
    name: kretprobe_test
    programId: 13395
    programLinkStatus: Success
    type: KRetProbe
  - name: tracepoint_test
    programId: 13396
    programLinkStatus: Success
    tracepoint:
      links:
      - linkId: 3264842258
        linkStatus: Attached
        name: syscalls/sys_enter_openat
        shouldAttach: true
        uuid: 1a2d782c-9c05-4ccb-a5d2-b92589fa5b7d
    type: TracePoint
  - name: tc_pass_test
    programId: 13398
    programLinkStatus: Success
    tc:
      links:
      - direction: Ingress
        interfaceName: eth0
        linkId: 2292281068
        linkStatus: Attached
        priority: 55
        proceedOn:
        - Pipe
        - DispatcherReturn
        shouldAttach: true
        uuid: 4fc3a458-c93b-404f-9227-4c367a560ec4
      - direction: Egress
        interfaceName: eth0
        linkId: 3243360575
        linkStatus: Attached
        netnsPath: /host/proc/2560/ns/net
        priority: 100
        proceedOn:
        - Pipe
        - DispatcherReturn
        shouldAttach: true
        uuid: 8b87e1ef-a0e5-4423-abed-68c99b528357
    type: TC
  - name: tcx_next_test
    programId: 13399
    programLinkStatus: Success
    tcx:
      links:
      - direction: Ingress
        interfaceName: eth0
        linkId: 1974385552
        linkStatus: Attached
        priority: 500
        shouldAttach: true
        uuid: 18bd4721-21d6-4d44-b229-c2e7d6c215bd
      - direction: Egress
        interfaceName: eth0
        linkId: 595062609
        linkStatus: Attached
        netnsPath: /host/proc/2560/ns/net
        priority: 100
        shouldAttach: true
        uuid: 6817600b-8681-474c-ba26-c6a3ebfedef7
    type: TCX
  - name: uprobe_test
    programId: 13400
    programLinkStatus: Success
    type: UProbe
    uprobe:
      links:
      - containerPid: 2456
        function: malloc
        linkId: 1114319296
        linkStatus: Attached
        offset: 0
        shouldAttach: true
        target: libc
        uuid: d713c6f1-9b57-4f31-a89a-6d87a9d36ddd
      - containerPid: 2401
        function: malloc
        linkId: 85632571
        linkStatus: Attached
        offset: 0
        shouldAttach: true
        target: libc
        uuid: 982c752b-8b09-409a-a494-d30b20cdad9a
  - name: uretprobe_test
    programId: 13401
    programLinkStatus: Success
    type: URetProbe
    uretprobe:
      links:
      - containerPid: 2456
        function: malloc
        linkId: 1248121244
        linkStatus: Attached
        offset: 0
        shouldAttach: true
        target: libc
        uuid: 13d299ce-86d0-45e2-b0ca-6563fef68b3f
      - containerPid: 2401
        function: malloc
        linkId: 1307762276
        linkStatus: Attached
        offset: 0
        shouldAttach: true
        target: libc
        uuid: 86eee9a7-8d03-4c9d-a12d-713ef16bb044
  - name: xdp_pass_test
    programId: 13403
    programLinkStatus: Success
    type: XDP
    xdp:
      links:
      - interfaceName: eth0
        linkId: 1916079109
        linkStatus: Attached
        priority: 55
        proceedOn:
        - Pass
        - DispatcherReturn
        shouldAttach: true
        uuid: a568d8ba-36f2-4b9f-9159-faa4dffb4088
      - interfaceName: eth0
        linkId: 4014676018
        linkStatus: Attached
        netnsPath: /host/proc/2560/ns/net
        priority: 100
        proceedOn:
        - Pass
        - DispatcherReturn
        shouldAttach: true
        uuid: 4d998752-ed83-4ec0-a6d5-14d6dc23f116
  - fentry:
      function: do_unlinkat
      links:
      - linkId: 3436717235
        linkStatus: Attached
        shouldAttach: true
        uuid: 93e04fe2-dc09-48dc-80e5-edbe87d9cfd1
    name: fentry_test
    programId: 13404
    programLinkStatus: Success
    type: FEntry
  - fexit:
      function: do_unlinkat
      links:
      - linkId: 1957573058
        linkStatus: Attached
        shouldAttach: true
        uuid: feffa69f-e843-4011-b97a-0cc487699f82
    name: fexit_test
    programId: 13405
    programLinkStatus: Success
    type: FExit
  updateCount: 3
