apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  labels:
    app.kubernetes.io/name: clusterbpfapplication
  name: clusterbpfapplication-sample-test3
spec:
  nodeSelector: {}
  byteCode:
    image:
      url: quay.io/bpfman-bytecode/app-test:latest
  programs:
    - name: kprobe_test
      type: kprobe
      kprobeInfo:
        links:
          - function: try_to_wake_up
            offset: 0
    - name: tracepoint_test
      type: tracepoint
      tracepointInfo:
        links:
          - name: syscalls/sys_enter_openat
    - name: fentry_test
      type: fentry
      fentryInfo:
        function: do_unlinkat
        links:
          - attach: true
    # - name: tcx_next_test
    #   type: tcx
    #   tcxInfo:
    #     links:
    #       - interfaceSelector:
    #           primaryNodeInterface: true
    #         priority: 500
    #         direction: ingress
