apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  labels:
    app.kubernetes.io/name: clusterbpfapplication
  name: clusterbpfapplication-sample-test3
spec:
  nodeSelector: {}
  byteCode:
    image:
      url: quay.io/bpfman-bytecode/app-test:latest
  programs:
    - name: kprobe_test
      type: Kprobe
      kprobe:
        links:
          - function: try_to_wake_up
            offset: 0
    - name: tracepoint_test
      type: TracePoint
      tracepoint:
        links:
          - name: syscalls/sys_enter_openat
    - name: fentry_test
      type: Fentry
      fentry:
        function: do_unlinkat
        links:
          - mode: "Attach"
    # - name: tcx_next_test
    #   type: TCX
    #   tcx:
    #     links:
    #       - interfaceSelector:
    #           primaryNodeInterface: true
    #         priority: 500
    #         direction: ingress
