name: pull request checks

on:
  pull_request:
    branches: ['*']

jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.21','1.22']
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: set up go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: checkout
      uses: actions/checkout@v3
    - name: check format
      run: make fmt && git add -A && git diff --exit-code
    - name: build, lint, test
      run: make build lint test
    - name: check clean vendors
      run: go mod vendor
    - name: Report coverage
      if: ${{ matrix.go == '1.21' }}
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./cover.out
        flags: unittests
        fail_ci_if_error: true
        verbose: true   

